version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - 8001:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=user_service
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  post-service:
    build: ./post-service
    ports:
      - 8002:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=post_service
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  api-gateway:
    build: ./api-gateway
    ports:
      - 8000:80
    depends_on:
      - user-service
      - post-service

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_service
      MYSQL_DATABASE: post_service
    ports:
      - 3306:3306
